# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Innovation District of Chattanooga
description: The first mid-sized city to designate an innovation district.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.chainnovate.com/" # the base hostname & protocol for your site
permalink: /:title/

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  directory_members:
    output: false
  
defaults:
  -
    scope:
      path: ""
      type: "directory_members"
    values:
      categories: ["Startup Support", "Arts & Culture", "Social Enterprise", "Business Development", "Collision Points", "Civic & Public", "Tech & Design"]
      filters: ["Funding", "Mentoring", "Training", "Networking", "Workspace"]
      member:
        name:
        bio:
        address:
        url:
      

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - gulpfile.js
  - _assets
  
# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
